version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: niman2-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-securepassword123}
      MONGO_INITDB_DATABASE: niman2-production
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - niman2-network

  # Backend API Server
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: niman2-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:${MONGO_ROOT_PASSWORD:-securepassword123}@mongodb:27017/niman2-production?authSource=admin
      ALLOWED_ORIGINS: ${FRONTEND_URL:-http://localhost:3000}
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - niman2-network
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend (for development/testing)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: niman2-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - niman2-network
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongodb_data:
    driver: local

networks:
  niman2-network:
    driver: bridge
